name: Build a WAR file using Maven and Deploy Java App to Tomcat running in AWS EC2

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    # Debug step (optional) - shows repo structure
    - name: List repo files
      run: ls -R

    - name: Build with Maven
      run: mvn clean install -f train-ticket-reservation/pom.xml

    - name: Deploy to Tomcat
      run: |
        curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
        -T train-ticket-reservation/target/TrainBook.1.0.0-SNAPSHOT.war \
        "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/train-ticket-reservation&update=true"
